version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: taskman-postgres
    environment:
      POSTGRES_USER: taskmanageruser
      POSTGRES_PASSWORD: taskmanagerpass
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanageruser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: taskman-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: taskman-backend
    volumes:
      - ./apps/backend:/app
      - /app/.venv  # Exclude venv from volume mount
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://taskmanageruser:taskmanagerpass@postgres:5432/taskmanager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  celery-worker:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: taskman-celery-worker
    volumes:
      - ./apps/backend:/app
      - /app/.venv
    environment:
      - DATABASE_URL=postgresql://taskmanageruser:taskmanagerpass@postgres:5432/taskmanager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.core.celery_app worker --loglevel=info -Q default,notifications,recurring,webhooks,analytics,reminders

  celery-beat:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: taskman-celery-beat
    volumes:
      - ./apps/backend:/app
      - /app/.venv
    environment:
      - DATABASE_URL=postgresql://taskmanageruser:taskmanagerpass@postgres:5432/taskmanager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.core.celery_app beat --loglevel=info

  flower:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: taskman-flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A app.core.celery_app flower

volumes:
  postgres_data:
  redis_data: